import React, { useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { saveItemsForCheckout, saveOrder } from "../../State/Action";
import CartListContainer from "../../Containers/Cart/CartListContainer";
import CartSummary from "../../Containers/Cart/CartSummaryContainer";

let CheckoutComponent = (props) => {

    //useState returns a stateful value and a function to update
    const [checkout, makePayment] = useState(true); //initialization of state through react hook useState passing in parameter
   
    let user = useSelector((state) => state.user.user);

    let cart = useSelector((state) => state.cart);

    let dispatchSaveOrder = useDispatch();

    const makePaymentClick = () => {
        makePayment(!checkout); //it will work as this.setState and propagate change to the react rendering engine eventually reflect the same
        //dispatchSaveOrder(saveOrder(cart, user._id));
        dispatchSaveOrder(saveItemsForCheckout(cart, user._id));
    }

    return(
        <div className="cartComponent">
            {checkout ? 
            <React.Fragment>
                <h1>Checkout Page</h1>
                <div>
                    Hi, <b>{props.user.userName}</b> 
                    {/* <p>Coming from useState {user.name +" "+user.age}</p> */}
                    <br/><p>
                    Your Items are checked out and will be delivered at below address.
                    <br/>
                    If it looks good then please proceed for payment.</p>
                    <hr/>
                    Mobile: <b>{props.user.mobile}</b>
                    <br/>
                    Adress: <b>{props.user.street}</b>
                    <hr />
                    {props.coupon ? 
                    <p>Coupon generated by you has been applied successfully : <b>{props.coupon}</b></p>
                    :<p>Please Generate Coupon to get discount.</p>}
                </div>
                <CartListContainer donotMakeEditable={true} />
                <CartSummary/>
                <div>
                    <button onClick={() => props.history.push("/cart")} >
                        Go Back To Cart
                    </button>
                    <button onClick={makePaymentClick} >
                        Make Payment
                    </button>
                </div>
            </React.Fragment> 
            :
            <React.Fragment>
                <h1>Payment Page</h1>
                <div>
                    Thankyou for the payment, your items under process!
                    <hr />
                    {/* <p>Coming from useState {user.name +" "+user.age}</p> */}
                </div>
                <div>
                    <button onClick={() => props.history.push("/cart")} >
                        Go Back To Cart
                    </button>
                    <button onClick={makePaymentClick} >
                        Go To Checkout
                    </button>
                </div>
            </React.Fragment>
            }
        </div>
    )
} 

export default CheckoutComponent;