export const AddUserToStore = "User.AddUserToStore";

//hobby
export const FETCH_HOBBY = "HOBBY.FETCH_HOBBY";
export const FETCH_HOBBY_FULFILLED = "HOBBY.FETCH_HOBBY_FULFILLED";

//product
export const FETCH_PRODUCTS = "PRODUCT.FETCH_PRODUCTS";
export const FETCH_PRODUCTS_FULFILLED = "PRODUCT.FETCH_PRODUCTS_FULFILLED";

//cart
export const ADD_ITEM = "CART.ADD_ITEM";
export const REMOVE_ITEM = "CART.REMOVE_ITEM";
export const UPDATE_ITEM = "CART.UPDATE_ITEM";
export const EMPTY_CART = "CART.EMPTY_CART";

//order
export const FETCH_ORDERS = "ORDER.FETCH_ORDERS";
export const FETCH_ORDERS_FULFILLED = "ORDER.FETCH_ORDERS_FULFILLED";
//export const REMOVE_ORDER = "ORDER.REMOVE_ORDER";

//cancel
export const FETCH_CANCELS = "CANCEL.FETCH_CANCELS";
export const FETCH_CANCELS_FULFILLED = "CANCEL.FETCH_CANCELS_FULFILLED";

//review
export const FETCH_REVIEW = "REVIEW.FETCH_REVIEW";
export const FETCH_REVIEW_FULFILLED = "REVIEW.FETCH_REVIEW_FULFILLED";